name: Generate Static Pages and PDF Thumbnails

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        sudo apt-get install -y imagemagick ghostscript
        mkdir -p assets/thumbs/zh-hant/{shuiling,bible,poetry,devotional} \
                 assets/thumbs/zh-hans/{shuiling,bible,poetry,devotional}

    - name: Generate PDF Thumbnails
      run: |
        function generate_thumbnails {
          local dir=$1
          local thumb_dir=$2
          for file in $dir/*.pdf; do
            [ -e "$file" ] || continue
            filename=$(basename "$file" .pdf)
            convert -density 150 "$file"[0] -thumbnail 200x200^ -gravity center -extent 200x200 "$thumb_dir/$filename.png"
          done
        }

        generate_thumbnails zh-hant/shuiling assets/thumbs/zh-hant/shuiling
        generate_thumbnails zh-hant/bible assets/thumbs/zh-hant/bible
        generate_thumbnails zh-hant/poetry assets/thumbs/zh-hant/poetry
        generate_thumbnails zh-hant/devotional assets/thumbs/zh-hant/devotional

        generate_thumbnails zh-hans/shuiling assets/thumbs/zh-hans/shuiling
        generate_thumbnails zh-hans/bible assets/thumbs/zh-hans/bible
        generate_thumbnails zh-hans/poetry assets/thumbs/zh-hans/poetry
        generate_thumbnails zh-hans/devotional assets/thumbs/zh-hans/devotional

    - name: Generate HTML Pages
      run: |
        function generate_html {
          local lang=$1
          local cat=$2
          local title=$3
          mkdir -p $lang/$cat

          cat > $lang/$cat/index.html << "HTML_EOF"
<!DOCTYPE html>
<html lang="zh-Hant">
<head>
  <meta charset="UTF-8" />
  <title>${title}</title>
  <link rel="stylesheet" href="../../assets/css/style.css" />
</head>
<body>
  <div class="container">
    <h1>${title}</h1>
    <div class="icon-grid">
HTML_EOF

          for file in $lang/$cat/*.pdf; do
            [ -e "$file" ] || continue
            filename=$(basename "$file")
            thumb="../../assets/thumbs/$lang/$cat/$(basename "$file" .pdf).png"
            echo "<a href=\"$filename\" class=\"icon\" download><img src=\"$thumb\" alt=\"$filename\"><span>$filename</span></a>" >> $lang/$cat/index.html
          done

          echo "</div></div></body></html>" >> $lang/$cat/index.html
        }

        generate_html zh-hant shuiling 屬靈書
        generate_html zh-hant bible 聖經難字粵音
        generate_html zh-hant poetry 詩歌
        generate_html zh-hant devotional 靈修資料

        generate_html zh-hans shuiling 属灵书
        generate_html zh-hans bible 圣经难字粤音
        generate_html zh-hans poetry 诗歌
        generate_html zh-hans devotional 灵修资料

    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --cached --exit-code || git commit -m "Auto-generate pages and thumbnails"
        git push
